apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-booking-service
  labels:
    app: doctor-booking-service
  annotations:
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor-booking-service
  template:
    metadata:
      labels:
        app: doctor-booking-service
    spec:
      serviceAccountName: doctor-booking-service
      containers:
      - name: doctor-booking-container
        image: dhanikanovlisa/doctor-booking:2.1
        ports:
        - containerPort: 8080
        env:
        - name: PINE_VALLEY_SERVICE_URL
          value: "http://pinevalleyservice/pine-valley"
        - name: GRAND_OAK_SERVICE_URL
          value: "http://grandoakservice/grand-oak"

---
apiVersion: v1
kind: Service
metadata:
  name: doctor-booking-service
  labels:
    app: doctor-booking-service
spec:
  selector:
    app: doctor-booking-service
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080