apiVersion: apps/v1
kind: Deployment
metadata:
  name: grandoakservice
  labels:
    app: grandoakservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grandoakservice
  template:
    metadata:
      labels:
        app: grandoakservice
    spec:
      serviceAccountName: grand-oak-service
      containers:
      - name: grand-oak-container
        image: dhanikanovlisa/grand-oak-service:2.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: grandoakservice
  labels:
    app: grandoakservice
spec:
  selector:
    app: grandoakservice
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001