apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinevalleyservice
  labels:
    app: pinevalleyservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pinevalleyservice
  template:
    metadata:
      labels:
        app: pinevalleyservice
    spec:
      serviceAccountName: pine-valley-service
      containers:
      - name: pine-valley-container
        image: dhanikanovlisa/pine-valley-service-go:2.1
        ports:
        - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: pinevalleyservice
  labels:
    app: pinevalleyservice
spec:
  selector:
    app: pinevalleyservice
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3002